#ifndef TCTOKENS_H
#define TCTOKENS_H

namespace toycalc {
  
   enum tokens{ ID, NUMBER, ADDOP, MULOP, RELOP, CHAR, RETURN, FOR, SWITCH, DEFAULT, STRING, LBRACKET, RBRACKET,
                WRITE, READ, IF, THEN, ASSIGNOP, INT, ELSE, DO, WHILE, CASE, CONTINUE, LCURLY, RCURLY, NOT, COMMA,
                COLON, SEMICOLON, LPAREN, RPAREN, EOFILE, BREAK, NEWLINE, CHARLITERAL, NONE };

}

#endif
